### ISSUE TITLE
Sharing an image

### ISSUE THREAD

**Issue by jdrydn** [alinz/react-native-share-extension#1]
So, sharing URLs from Safari or any in-app browser works really well!

How about other forms of content? Images, for example? I'm trying with an image from the simulator but `ShareExtension.data()` appears to just hang... is there any point where I can enable some form of debugging to try and work out what's going on within the `ShareExtension` class?

**Comment by jdrydn** [comment]
I may not be an iOS developer, but [these lines](https://github.com/alinz/react-native-share-extension/blob/master/ios/ReactNativeShareExtension.m#L41-L53) suggest this is only for URLs and not for other forms of content. Fortunately that's completely fine for me, but is there any way to trigger the `RCTPromiseRejectBlock` if the content being shared is not a URL?

**Comment by alinz** [comment]
@jdrydn That is correct. My use case was only for URL. I'm up for a nice PR. 👍 
if you plans to write one for iOS, would you mind write one for android as well. I want to keep the features the same for both platform.

For your question, there are couple of things we can do. The good news is `value` comes with type. so one option would be passing the path of the image back and you can either show it on share extension view or using network api to upload it to server. Remember, share extension must be as light as possible,

**Comment by jdrydn** [comment]
Given my inexperience with Objective-C, I'm definitely not the best person to try writing "_light as possible_" code 😜

However you **can** use the extension's `Info.plist` to limit your extension to only receiving URLs, [as this Apple developer documentation explains](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW8), like so:

```
<key>NSExtensionAttributes</key>
<dict>
  <key>NSExtensionActivationRule</key>
  <dict>
    <key>NSExtensionActivationSupportsWebURLWithMaxCount</key>
    <integer>1</integer>
  </dict>
</dict>
```

This means it'll only show your extension for apps sharing a single URL, and other apps (like Photos) won't be able to share content with your extension. Which is perfect for this codebase (because `context.inputItems firstObject`) 😄 

This is definitely a short-term solution, or only applicable to apps that only want URLs?

@alinz: It could be worth adding this to the README if this was only designed for URLs?

**Comment by alinz** [comment]
@jdrydn thanks for feedback. The thing is you can not publish your app to App Store if you don't set that one right. That's one the reason I did that. This is a limited configuration and it's not enough. What if you want to share from notes app which has some URLs? you can still grab those and process the urls in JS code.

Any changes to iOS must be reflected to Android as well. I don't want to have a specific API for android and iOS. 

I'm closing this ticket but if you want you can make a PR and I would be happy to merge it.

cheers
