### ISSUE TITLE
Seeking couple of people to help me push this library forward

### ISSUE THREAD

**Issue by alinz** [alinz/react-native-share-extension#102]
Hello,
I'm seeking for couple of contributors to help me resolve couple of issues and push this library forward.

Please comment on this issue and I will will in contact with you shortly.

Thanks

**Comment by AndrewHenderson** [comment]
@alinz I'm interested.

**Comment by alinz** [comment]
@AndrewHenderson I have made you Collaborator. Also send me your npm username if you have one.

**Comment by alinz** [comment]
@AndrewHenderson we should also create a roadmap for this module. If you can do that then I can priorities my time to work on it.

**Comment by fishkingsin** [comment]
@alinz I'm in

**Comment by alinz** [comment]
@fishkingsin this is amazing, would you send me your NPM username as well.

**Comment by fishkingsin** [comment]
@alinz "fishkingsin"
