### ISSUE TITLE
Does share extension work with react native navigation v1 (wix)?

### ISSUE THREAD

**Issue by i25878427** [alinz/react-native-share-extension#114]

**Comment by i25878427** [comment]
I upgraded to react native navigation v2 (wix) and it did the trick for me :)

**Comment by ekeuus** [comment]
@i25878427 Hey Ron! Were you able to share the files with the main application? I'm trying to get it to work with v2 as well. Thanks!

**Comment by i25878427** [comment]
@ekeuus yes, what is the problem?

**Comment by ekeuus** [comment]
I want to share directly to the app, not into the app registry component, but I can't think of a good solution to do so

**Comment by i25878427** [comment]
Not sure how it can be done. Maybe URL TYPES?
