### ISSUE TITLE
[ios] - Timed out waiting for modules to be invalidated

### ISSUE THREAD

**Issue by NHuyHoang** [alinz/react-native-share-extension#128]
Hi guys, thanks for creating this libraries. I have installed this library following the README.md. When I build my main app it start with a blank screen for a while after that there is a error  "Timed out waiting for modules to be invalidated". I wonder is this share-extensions view be displayed in the beginning ?  

<img width="353" alt="screen shot 2018-11-27 at 11 45 01 am" src="https://user-images.githubusercontent.com/22568742/49059117-e727c100-f239-11e8-807b-9fbf366b61e3.png">

Here is my setting
<img width="1340" alt="screen shot 2018-11-27 at 11 33 11 am" src="https://user-images.githubusercontent.com/22568742/49059233-73d27f00-f23a-11e8-9100-4668d5ea238a.png">

<img width="848" alt="screen shot 2018-11-27 at 11 30 59 am" src="https://user-images.githubusercontent.com/22568742/49059135-032b6280-f23a-11e8-94dc-f1aaeaa60d97.png">

<img width="1302" alt="screen shot 2018-11-27 at 11 30 34 am" src="https://user-images.githubusercontent.com/22568742/49059185-42f24a00-f23a-11e8-9d5e-2cdb6f01c51d.png">

<img width="799" alt="screen shot 2018-11-27 at 11 31 15 am" src="https://user-images.githubusercontent.com/22568742/49059212-5ef5eb80-f23a-11e8-9eaf-8bb633f5f655.png">

<img width="950" alt="screen shot 2018-11-27 at 11 32 13 am" src="https://user-images.githubusercontent.com/22568742/49059264-982e5b80-f23a-11e8-8f8a-90222a43d92b.png">
<img width="945" alt="screen shot 2018-11-27 at 11 32 37 am" src="https://user-images.githubusercontent.com/22568742/49059265-982e5b80-f23a-11e8-93cf-9cea03f435d5.png">

**Comment by frenberg** [comment]
I asked google about the error message you are getting, and it seams to be related to styling or some other stuff in your javascript-file. I don't think it is related to this library.

**Comment by NHuyHoang** [comment]
Thanks @frenberg, you are right. I have checkout for the previous branch. It is the error I got before install this library. Going to close this issue. Thank you so much.
