### ISSUE TITLE
Can this lib be used to share things from other apps ?

### ISSUE THREAD

**Issue by leiz-me** [alinz/react-native-share-extension#138]
Just want to make sure if this is the current status.

#96 mentioned some point but no solution found.

**Comment by isaachinman** [comment]
What status? Quite a few of us are using this project in production to share links, images, and videos from other apps into our own apps. What is your question?

**Comment by leiz-me** [comment]
Sorry not make it clear. My problem is that I can only see the share extension in the browser but not from other apps, even though added the rule settings in info.plist and androidmanifest.

What did I miss?
