### ISSUE TITLE
Wix react-native-navigation v2 support?

### ISSUE THREAD

**Issue by prabakarviji** [alinz/react-native-share-extension#139]
When trying to integrate sharing extension with react-native-navigation, we are getting this issue 

`com.example.extension.ExampleExtensionActivity cannot be cast to com.reactnativenavigation.NavigationActivity`

**Comment by mtzfactory** [comment]
I tried as well without success... Make it work with react-native-navigation v2 would be amazing...

**Comment by i25878427** [comment]
It is working with react-native-navigation v2 and not with v1 from my personal experience.

**Comment by prabakarviji** [comment]
@i25878427 What about android?

**Comment by i25878427** [comment]
I haven’t tried it but I believe it should work

**Comment by prabakarviji** [comment]
@i25878427 I tried it and it doesn't work as expected

**Comment by mtzfactory** [comment]
@i25878427 can you post an small example? Thanks

**Comment by i25878427** [comment]
Just follow the installation guide for the SE and just use react-navigation **v2** and not v1 and it should work for you ( you don't need to do anything special :) )

**Comment by prabakarviji** [comment]
@i25878427 Can you help me on this?

**Comment by i25878427** [comment]
@prabakarviji What do you need? If it is Android related, I have no experience with it.

**Comment by Asleepace** [comment]
any update on this?

**Comment by isaachinman** [comment]
@Asleepace What kind of update are you hoping for? This package is not actively maintained for the most part, and from the comments in this issue it seems to be a setup problem.

**Comment by Asleepace** [comment]
@isaachinman just wondering if anyone managed to get this working with V2
