### ISSUE TITLE
Question on communication with share.ios.js and app.ios.js

### ISSUE THREAD

**Issue by iou90** [alinz/react-native-share-extension#14]
Actually, this isn't an issue, just wonder how you communicate with share.ios.js and app.ios.js. I want to pass the value to the app.ios.js when data received in share.ios.js.

I'm new to RN, have tried events (Emitter) and global variables but neither works.
I think these components have separate JS environment ?

**Comment by balasan** [comment]
I just managed to share the user auth token for api calls between the app and the share extension

You have to enable groups in your app: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html
(see "Configuring App Groups section")

and then use this library https://github.com/wwayne/react-native-user-defaults
to store data that is accessible to both the app and the extension

one more ref: http://stackoverflow.com/questions/24118918/sharing-data-between-an-ios-8-share-extension-and-main-app

**Comment by alinz** [comment]
@iou90 for our app, what I did was using this module [react-native-swiss-knife](https://github.com/alinz/react-native-swiss-knife). I use the bucket feature of that one which enables me to share object between share extension and app. It works for both ios and android.

before you can do this, make sure you create a group as @balasan mentioned.

**Comment by iou90** [comment]
@balasan @alinz thx for helping! I'll give it a try with your advice.

**Comment by alinz** [comment]
@iou90 closing this issue and I'm assuming it got fix. reopen it again if you have the problem again.
