### ISSUE TITLE
Help needed making Sample1 example works on Android

### ISSUE THREAD

**Issue by arribbar** [alinz/react-native-share-extension#15]
Hi,

I tried your example on Android and I did not succeed to make it work.
I have:
- "react": "15.3.1",
- "react-native": "0.32.0",

When I try to share either an url or an image, in the share.android.js, in `componentDidMount` function, ShareExtension is not defined. I got this error : 
```
errrr TypeError: Cannot read property 'data' of undefined(…)
```

Do you know how to solve this error?

**Comment by work2fork** [comment]
+1, ShareExtension is not defined only on Android

**Comment by arribbar** [comment]
Any hint @alinz ?

**Comment by arribbar** [comment]
I figured out my problem.
We need to import and add SharePackage in MainApplication.java

```
import com.alinz.parkerdan.shareextension.SharePackage;
```

```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new SharePackage()
      );
    }
```
I'll make a PR to improve the documentation about that.
Hope it'll help you
