### ISSUE TITLE
npm does not have the newest version

### ISSUE THREAD

**Issue by viestat** [alinz/react-native-share-extension#16]
I see on the repo that on the most recent [pull request](https://github.com/alinz/react-native-share-extension/commit/907387ef0339967bde1e3e7ae05a2777ae167373), the sharing an image functionality was added. It would be great to have the newest version on npm.

Thank you for this nice module!

**Comment by alinz** [comment]
I have publish 1.1.0 and 1.1.1 to target 0.39 and 0.40
