### ISSUE TITLE
IOS Share Extension not launch app.

### ISSUE THREAD

**Issue by andersonqi** [alinz/react-native-share-extension#160]
Hi there!
share extension works if I replace my app with a very basic component. But if I use my full app with react navigation etc it does not work. When I try the screen stays frozen.

Is there a problem if I use react navigation? I feel that it blocks the flow

**Comment by NishidaRyu416** [comment]
Don’t you have the same keys to `registerComponent` methods in order to register both your share extension and app components?
If yes, it doesn’t work well because the component before is overridden by the one after that or simply causes a conflict.

A bad anticipated example:
```
//index.ios.js
import React from 'react'
import { AppRegistry } from 'react-native'

import App from './app.ios'
import Share from './share.ios'

AppRegistry.registerComponent('Sample1', () => App)
AppRegistry.registerComponent('Smaple1', () => Share) // TODO: Replace MyShareEx with my extension
```
A fine estimated example:
```
//index.ios.js
import React from 'react'
import { AppRegistry } from 'react-native'

import App from './app.ios'
import Share from './share.ios'

AppRegistry.registerComponent('Sample1', () => App)
AppRegistry.registerComponent('Share', () => Share) // TODO: Replace MyShareEx with my extension
```

**Comment by andersonqi** [comment]
Yes, that was my mistake

Thank you @NishidaRyu416

**Comment by Shaktis3** [comment]
Hey i'm facing the same issue. Will you please help to resolve it. Thanks in advance.

**Comment by andersonqi** [comment]
@Shaktis3 my problem was that I had the wrong name in the register and the share. Verify that all names are correct.

**Comment by Shaktis3** [comment]
Yes. In my case all the thing are correct. but still not able to open app or any screen when clicked on share extension. It freezes the app through which i'm sharing the content.

**Comment by ramon90** [comment]
@Shaktis3 did you find a fix?
