### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by djorkaeffalexandre** [alinz/react-native-share-extension#163]
In android if I put a console.log on ComponentDidMount this show but not show the view of render.

**Comment by ramon90** [comment]
Same for me, and also app crashes! Not working on ios either

**Comment by djorkaeffalexandre** [comment]
Hi @ramon90 , I resolved the problem on Android, is on Share Theme... If you want to use this library, I have a fork and maintain it to use on [Rocket.Chat.ReactNative](https://github.com/RocketChat/Rocket.Chat.ReactNative), you can find examples on [RocketChat Share Extension (iOS)](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/942)..
My fork of this library is: [rn-extensions-share](https://github.com/RocketChat/rn-extensions-share)

**Comment by ramon90** [comment]
@djorkaeffalexandre Thanks for your reply, and sorry for my late reply. I will check it " rn-extensions-share" out. Does it also work using firebase?

**Comment by djorkaeffalexandre** [comment]
@ramon90 yeah! In [Rocket.Chat.ReactNative](https://github.com/RocketChat/Rocket.Chat.ReactNative) we use Firebase :)

**Comment by ramon90** [comment]
@djorkaeffalexandre so I tried it on ios, but I am still facing the same issue I had before, the share extension appears in the share menu, but when I press it nothing happens. I have followed the installation guide exactly. Is there any further steps that you have done to get it working on ios?

**Comment by djorkaeffalexandre** [comment]
@ramon90 can you give me your repository url to help you?

**Comment by ramon90** [comment]
@djorkaeffalexandre Thank you I fixed the issue. Just one question, on iOS I am using a modal to show the share extension, but it appears without animation, I have the animation module included, also I can run animations within the modal normally. Any clue on that?

**Comment by djorkaeffalexandre** [comment]
Which is your animation module?

**Comment by ramon90** [comment]
@djorkaeffalexandre libRCTAnimation.a

**Comment by djorkaeffalexandre** [comment]
Probably that: https://github.com/alinz/react-native-share-extension/issues/99
Which is your react-native version?

**Comment by ramon90** [comment]
` "react": "16.8.3",
    "react-native": "^0.59.9",`

**Comment by djorkaeffalexandre** [comment]
Here animation works fine: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/1064#issue-299415237
Can you try to use `react-native-modalbox` instead `modal` from `react-native`?

**Comment by ramon90** [comment]
@djorkaeffalexandre I tired both

**Comment by ramon90** [comment]
@djorkaeffalexandre ok I will try it there

**Comment by djorkaeffalexandre** [comment]
Oh :( can you give me a gif?

**Comment by ramon90** [comment]
@djorkaeffalexandre I am getting a warning "Module MyShareEx requires main queue setup since it overrides 'init' but doesn't implement 'requiresMainQueueSetup'. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.'
Could it be related to that warning? Are you getting this same warning?

**Comment by ramon90** [comment]
@djorkaeffalexandre I tried the native Modal component and it is working. Thank for your help. But do you have any clue on this warning?

**Comment by djorkaeffalexandre** [comment]
yes, i get the same warning, it is not related to it, to fix this i will soon release a new release of `rn-extensions-share` with this:
`
+ (BOOL)requiresMainQueueSetup
 {
     return YES;
 }
`
some of the React-Native libraries don't work on iOS because Share Extension doesn't have access to sharedApplication in objective-c

**Comment by ramon90** [comment]
@djorkaeffalexandre Aha okay, Thanks a lot for your time, I appreciate it :)

**Comment by ramon90** [comment]
Hello @djorkaeffalexandre, the library does not support sharing of multiple images, I was able to add support for that on android, but I could not do it on iOS. Where you able to add support for multiple images on iOS?
