### ISSUE TITLE
IOS APP FREEZES

### ISSUE THREAD

**Issue by ramon90** [alinz/react-native-share-extension#172]
I have followed all the steps in the installing guide, I get the share extension in the share menu, but when i press on it safari freezes completely. Any help is appreciated :'(

**Comment by ramon90** [comment]
So I figured it out, the app does not freeze the background was just transparent. That was tricky it should be added to the docs.

**Comment by ramon90** [comment]
Anyone using this library with react native 0.59.9? I can not get it to work..

**Comment by vivek25constants** [comment]
Did it work for you?

**Comment by colaskirschoff** [comment]
@ramon90 did you manage to fix this or areyou using another library ?

**Comment by OmarBasem** [comment]
@colaskirschoff this library only supports sharing urls, and is very limited, so I ended up creating my own share extension using native code.
