### ISSUE TITLE
Upgrade to AndroidX as it does not work RN => 0.59

### ISSUE THREAD

**Issue by kumbhar-ketan** [alinz/react-native-share-extension#181]
Please refer this link to upgrade to AndroidX.
https://github.com/react-native-community/discussions-and-proposals/issues/129#issuecomment-495686282

**Comment by ajith-ab** [comment]
i ve used this package  with all new features with react native greater than 0.60 support  [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by kumbhar-ketan** [comment]
@ajith-ab This package worked => 0.59.0 version. I found a solution. It is there in the document. But thanks for your suggestion.
