### ISSUE TITLE
Image sharing on iOS returns no data

### ISSUE THREAD

**Issue by louiscenter** [alinz/react-native-share-extension#20]
Back in September, @parkerdan kindly contributed a PR adding image support, which was merged by @alinz.

After testing this on both iOS 10.1 and and 9.3, it seems that `data()` doesn't return anything when you share an image from the Photos app. Sharing a URL from Safari works fine however.

I know next to nothing about coding in Objective C. Looking through `ios/ReactNativeShareExtension.m`, I wonder whether the `url` variable isn't working as expected before it's passed into the `callback`, or if there's something else at play?: https://github.com/alinz/react-native-share-extension/blob/907387ef0339967bde1e3e7ae05a2777ae167373/ios/ReactNativeShareExtension.m#L83-L90

Is there something else that needs to be enabled first for image sharing to work?

**Comment by parkerdan** [comment]
There is an issue with getting the proper content files from NPM.

Go into YOUR `node_modules => react-native-share-extension => ios => ReactNativeShareExtension.m` <br>
I'm guessing your version of that file ^^ does not match the file in the link you pasted above.

I just created a new project to test this issue and the proper files didn't come from NPM.  After pasting the proper file in, all is well...

-Dan

![screen shot 2016-12-11 at 8 20 00 am](https://cloud.githubusercontent.com/assets/12119980/21080666/b7eccfb4-bf7a-11e6-9303-585bee087853.png)

```js
import React from 'react'
import Alert from 'rn-animate-alert'
import { View,Text,TouchableOpacity } from 'react-native'
import ShareExtension from 'react-native-share-extension'

export default class Share extends React.Component {


  constructor(){
    super()
    this.state = {
      show: false,
      type: '',
      value: '',
    }
  }

  async componentDidMount(){

    try {
      let { type, value } = await ShareExtension.data()
      
      this.setState({type:type,value:value, show:true})
    } catch (e){
      console.log(e)
    }
  }

  close = () => {
    this.setState({show:false}, () => ShareExtension.close() )
  }

  render(){
    let { type, value, show } = this.state
    return(
      <Alert
        show={ show }
        entrance={ 'fromBottom' }
        backgroundColor={ 'rgba(111,111,111,.7)' }
      >
        <View style={{
          marginVertical:100,
          marginHorizontal:30,
          backgroundColor:'white',
          padding:10,
          alignItems:'center',
          justifyContent:'center',
          flex:1,
        }}>
          <Text>{type}</Text>
          <Text>{value}</Text>
          <TouchableOpacity onPress={ this.close }>
            <Text>{'CLOSE'}</Text>
          </TouchableOpacity>
        </View>
      </Alert>
    )
  }
}

```

**Comment by louiscenter** [comment]
@parkerdan I feel silly for not picking up on this myself 😅 Thank you for pointing this out! Maybe I should file an issue asking for @alinz to do a fresh `npm publish`?

**Comment by alinz** [comment]
@louiscenter I have publish to npm, this should be fixed now.
