### ISSUE TITLE
expo-dev-client / EAS build integration?

### ISSUE THREAD

**Issue by keredson** [alinz/react-native-share-extension#215]
expo is now supporting native code w/o ejecting.  any thoughts on if this extension can work w/ it?

https://docs.expo.io/build/introduction/
https://docs.expo.io/clients/introduction/#what-youll-gain-by-adopting--expo-dev-client

example: https://github.com/dotintent/react-native-ble-plx/pull/842
https://expo.canny.io/feature-requests/p/bluetooth-1

**Comment by artemn9** [comment]
It works with EAS in both production and dev-client, I confirm. Set it up for myself two weeks ago successfully.

Follow instructions https://github.com/alinz/react-native-share-extension/issues/182 after you do expo prebuild --no-install.
