### ISSUE TITLE
Crash in production...

### ISSUE THREAD

**Issue by adrianotadao** [alinz/react-native-share-extension#23]
@alinz Hi man, sorry to bother you again.

Do you know or, have you heard someone talking about the crash when using Fastlane? I have added the script to build local on my device... at this point, everything is okay but, when I'm using Fastlane to deploy my app to the testers, the extension is not opening =l

What is the best way to debug it? 

Ps. Odin, help me! 🙏  😂

**Comment by adrianotadao** [comment]
I'm so dumb. I can change the schema to use the release instead of debugging.

**Comment by alinz** [comment]
lol

**Comment by npomfret** [comment]
Did you find what was wrong?  Mine is crashing when deployed through fastlane also

**Comment by npomfret** [comment]
Oh ok.  My problem is that it works fine in dev.  But when I send to fastlane it crashes.  The UI appears but it looks like when calling `ShareExtension.data()` it fails.  At least I don't see the shared data appearing on screen before the crash happens.  Very strange.

**Comment by adrianotadao** [comment]
React native sometimes is sucks... it shows us generic errors. Another day I was receiving an error and when I decided to do a deep check I realized that the problem was inside the Intercom plugin. Always after this day, I check the libs almost before all. 

Another big mistake that we stopped here is to add dependencies like. `'foo', '^1.0.1'` ... we had a problem with the update of libs, so, nowadays we just put specific versions. Never more use '^1.0.1', we use just '1.0.1'.

**Comment by npomfret** [comment]
Agreed, never use wildcards in your dependencies - it's just madness.

I'm confident my libs are ok because it works when I run it outside of fastlane.  

I even see the ui appear when running in fastlane... but no data and then a crash.  I've added crashlytics but nothing still...

**Comment by adrianotadao** [comment]
hum... sorry man, I can't help you. There are a bunch of errors that I have no idea why. =l
