### ISSUE TITLE
Import errors on build (iOS)

### ISSUE THREAD

**Issue by Tyrdall** [alinz/react-native-share-extension#29]
Hi,

I'm running into several import issues, while trying to create a build for iOS, for example: React/RCTBridgeModule.h file not found
I've tried everything from react-native 0.37.0 - latest.

Is there a version stack of react and react native you usually use for this app?

Thanks in advance!

**Comment by alinz** [comment]
This is a common problem with upgrading to new version of react-native. For react-native version 0.39 and below use `react-native-share-extension@1.1.0` for react-native@0.40 and above use `react-native-share-extension@1.1.1`

**Comment by Tyrdall** [comment]
@alinz Thanks for the fast response.
I installed all latest versions, but those errors are still the case. :(

    "dependencies": {
        "react": "15.4.2",
        "react-native": "0.42.3",
        "react-native-share-extension": "^1.1.1"
    },

Those issues are popping up everywhere on the web, so I'll keep my eyes peeled for a possible solution.

**Comment by Tyrdall** [comment]
It works now. I actually don't know what fixed it. I played around in Xcode and somehow the build went through recently.
Sorry for the trouble :(

**Comment by alinz** [comment]
@Tyrdall glad that you fix this, if you found the actual problem, would you please post it here as a documentation. Cheers!

**Comment by Rutulpatel7077** [comment]
I am having same issue..
