### ISSUE TITLE
Updates/corrections to README.md

### ISSUE THREAD

**Issue by allenrl** [alinz/react-native-share-extension#3]
First off, thanks for sharing this code -- I really needed it!  As a relative newbie to RN, iOS and Android dev I followed your readme quite closely and noticed two corrections:

> we need to add some flags as well, so search for Other Linker Flags and add **-Objc** and -lc++

-Objc should be properly cased to capital O and capital C:  **-ObjC** (good thing there was a screenshot, but my eagerness to blindly copy/paste sent me down a debugging rabbit-hole for a day or so :) You only get an error indicating there's a problem if you run in Xcode with the extension as the target -- if you run with the app as the target, it fails silently.

Second, minor correction, in your code snippet for MyShareEx.m:
> * now go back to MyShareEx.m and paste the following code there.
```
...
@interface MyShareEx : ReactNativeShareExtension
@end
@implementation MyShareEx
- (UIView*) shareView {
..
```

need to include 'RCT_EXPORT_MODULE();' in between '@implementation MyShareEx' and
'- (UIView*) shareView {'  to read:
```
...
@interface MyShareEx : ReactNativeShareExtension
@end

@implementation MyShareEx
RCT_EXPORT_MODULE();
- (UIView*) shareView {
...
```
RCT_EXPORT_MODULE(); is in the [actual file](https://github.com/alinz/react-native-share-extension/blob/master/examples/Sample1/ios/MyShareEx/MyShareEx.m), but again, if someone copy/pasted from the readme, they would have missed it...luckily this was not a showstopper and did not break the module.

**Comment by alinz** [comment]
thanks @allenrl. Would you send me a PR for those typo. Example was the best source of truth.

One more thing. if you need to share some data between your app and the share extension you can take a look at [react-native-swiss-knife](https://github.com/alinz/react-native-swiss-knife). Look into RNSKBucket.

**Comment by allenrl** [comment]
d'oh you beat me to it, @alinz !  thanks and i'll be sure to check out RNSBucket.
