### ISSUE TITLE
Android Build error "method does not override or implement a method from a supertype"

### ISSUE THREAD

**Issue by allenrl** [alinz/react-native-share-extension#4]
Hi @alinz -- I tried to start a fresh new RN project and use the extension, but when I attempt to build it with 'react-native run-android', I keep getting the error:

```
:react-native-share-extension:compileReleaseJavaWithJavac
:react-native-share-extension:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/NEW_RN_APP/node_modules/react-native-share-extension/android/src/main/java/com/github/alinz/reactNativeShareExtension/ShareExActivity.java:78: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-share-extension:compileReleaseJavaWithJavac FAILED
```

Are you familiar with this error or how I might troubleshoot it?  Thanks!

**Comment by allenrl** [comment]
update: don't know if this is just a coincidence or the cause, but RN just pushed a new update v 0.29.0 just a few days ago that might explain why this error happened when I just generated a new RN app yesterday and installed your extension.  the update creates a new file MailApplication.java that contains some code similar to what it was complaining about during the build (@Override protected List<ReactPackage> getPackages()).  
v 0.29.0 Update Release Notes:  https://github.com/facebook/react-native/releases/tag/v0.29.0

quote:

> Android
> 
> Change the application template (49f20f4) - @foghina
> 
> Plugins which pass activity reference in the constructor need to be updated to extend ReactContextBaseJavaModule use getCurrentActivity to get the activity reference. This change is backward compatible.
> Apps need to be migrated to use the latest template
> Migration instructions for apps
> 1. Create a new file MainApplication.java in the same folder as MainActivity.java
> 2. Update it to match - https://github.com/facebook/react-native/blob/0.29-stable/local-cli/generator-android/templates/package/MainApplication.java and move your customisations from MainActivity.java to this file
> 3. Update MainActivity.java to match - https://github.com/facebook/react-native/blob/0.29-stable/local-cli/generator-android/templates/package/MainActivity.java

**Comment by alinz** [comment]
@allenrl yes that is true. The bootstrap api for Android has been changed significantly. I will update the code soon. Once I push the code I will close this ticket.

**Comment by allenrl** [comment]
hi @alinz just checking in to see if you have a fix any time soon.  if not, but you know how to fix it, can you provide a brief explanation or simple instructions and i'll see if i can make it work?  thanks!

**Comment by zekchan** [comment]
+

**Comment by southernvg** [comment]
Hi @alinz,  I would also love if you would update to handle the new bootstrap,  or maybe if you have some ideas on a work around.   I have your extension up and running on iOS work great.   But my RN is at .30.   Thank you.

**Comment by work2fork** [comment]
+

**Comment by MalNe** [comment]
Hi, alinz!
For our project we really need this issue to be resolved - is there any possibility that you finish it? 
If there are some problems that cause this delay or somethig?
Million thanks in advance!!

**Comment by goodhyun** [comment]
+1

**Comment by hyelong** [comment]
+1

**Comment by waleedarshad-vf** [comment]
+1

**Comment by alyrik** [comment]
+1. Still waiting for update.

**Comment by luisfuertes** [comment]
I have the same issue with:
``` 
"react": "15.3.2",
"react-native": "0.33.0",
"react-native-share-extension": "^1.0.3",
```

**Comment by ChrisPikul510** [comment]
I'm going to assume this project has been abandoned. Would like to see this come back if possible, tag me if anybody figures out a fix.

**Comment by alinz** [comment]
I have published 2 version 1.1.0 for react-native 0.39 and below and 1.1.1 for react-native 0.40.0 and above.

**Comment by alinz** [comment]
@ChrisPikul510 just because I haven't published anything on npm doesn't mean I have abandoned this project. As you know, I have other priorities as well, so you can easily do a fork and build everything on top of it and if you want you can give me a PR.

**Comment by luisfuertes** [comment]
Now it works perfect with:
``` 
"react": "15.3.2",
"react-native": "0.33.0",
"react-native-share-extension": "^1.1.0",
```

**Comment by alinz** [comment]
@luisfuertes please make sure to remove the `^` from the version in your package.json.

**Comment by allenrl** [comment]
@alinz -- for those of us that encountered this error when building our RN app on version <0.29, can we resolve this issue by updating/upgrading your extension and RN to the latest version?  or, do we need to start over by creating/building a brand new RN app?

**Comment by alinz** [comment]
@allenrl I think you should be able to use 1.1.0. Give it a try. the thing is I can't support every single version. I need the community to support me. try it and let me know, and if you can fix any problem I would be gladly accept your PR.
