### ISSUE TITLE
Crashing when closing extension on Android

### ISSUE THREAD

**Issue by brenwarwcdg** [alinz/react-native-share-extension#43]
When running the following code in the Share Extension on Android:

`close = () => {
    ShareExtension.close()
  }`
...
`render() {`
...
`<TouchableOpacity onPress={this.close}>`
...

The app crashes with the error message:

`undefined is not an object (evaluating '_reactNative.nativeModules.ReactNativeShareExtension.close')`

**Comment by alinz** [comment]
Have you import the modules in either xcode or android studio? close function is an exported function coming from native side.

**Comment by brenwarwcdg** [comment]
This might be why it works on iOS and not Android, is the expected implementation in ShareApplication.java?

**Comment by alinz** [comment]
have you read and apply all the required settings in here [android doc](https://github.com/alinz/react-native-share-extension#android). Also have you tried with sample project? Are you still getting an error? I think you missed one important things from doc, Check it again.

**Comment by brenwarwcdg** [comment]
Pretty sure I've applied all steps in the sample doc. Once I did it all I ran through Android Studio, which installed all the dependencies through gradle for me.

Also after trying to set up the project it seemed to halt on the device, refusing to open, but based off the example PROJECT everything looks fine..

**Comment by alinz** [comment]
@brenwarwcdg if you can create an project example in github and send the url to me so I can debug it and see if I can find a solution for it. That's the only thing I can help you with.

**Comment by brenwarwcdg** [comment]
Thank you very much for offering. I'm porting it over now..

**Comment by brenwarwcdg** [comment]
Recreating this issue in another project has made me realise I missed adding the `new SharePackage()` to `protected List<ReactPackage> getPackages()`. Closing issue now..
