### ISSUE TITLE
Crashing on iOS by FB Bolts lib 

### ISSUE THREAD

**Issue by mferranti** [alinz/react-native-share-extension#46]
Hello, i am having a trouble with the share extension and other libs i hope to have an answer here.
When I open the extension it fails because there are missing libraries (the ones I use in the main app, such as google-sign-in, FBSDK, etc). If i add the missing libraries to the extension target, 
Xcode will not let me build because "Shared Application" (used in Facebook Bolts lib) is not available in the extension.

log-ios if not include lib on target:
```
<Warning>: Warning: Native component for "RCTFBLikeView" does not exist
<Warning>: Warning: Native component for "RCTFBLoginButton" does not exist
<Warning>: Warning: Native component for "RCTFBSendButton" does not exist
<Warning>: Warning: Native component for "RCTFBShareButton" does not exist
<Error>: Native module cannot be null.
<Critical>: Unhandled JS Exception: Native module cannot be null.
<Notice>: Running application TaringaShare ({
	    initialProps =     {
	    };
	    rootTag = 1;
	})
<Error>: Module AppRegistry is not a registered callable module (calling runApplication)
<Critical>: Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)
```

Xcode error if include lib:
```
/path-to-ios-project/Pods/Bolts/Bolts/iOS/BFAppLinkReturnToRefererView.m:143:49: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```

I'm doing something wrong?

Thanks!!

**Comment by alinz** [comment]
This is not really the share extension issue, but what I would suggest is if you can find someone who actually uses these SDK along with native share extension. if you find one, then I will look into it and see what they have done and replicate the result.

**Comment by alinz** [comment]
@mferranti can you look into this [issue](https://github.com/alinz/react-native-share-extension/issues/48), I think this trick might resolve your problem

**Comment by mferranti** [comment]
Nice trick! that issue seems similar to mine. I'm gonna to try it this week!

**Comment by mferranti** [comment]
@alinz yeah!!! that trick works perfect to me. You can close this issue now. 
A lot of thanks.
