### ISSUE TITLE
On iOS: Native module cannot be null

### ISSUE THREAD

**Issue by itaibs** [alinz/react-native-share-extension#48]
Hi,

We're experiencing an issue with our iOS share extension (android works perfectly) where when we try to use the extension it seems that nothing happens. When checking the system logs we get an error saying "Native module cannot be null".

After that it says: Module AppRegistry is not a registered callable module (calling runApplication)

We are linking all of the libraries, as far as I can tell. Moreover, everything already worked fine before. 

Any idea what might cause such an error?

**Comment by alinz** [comment]
@itaibs, when I usually upgrade react-native, I found out sometimes, some of the modules are not linked properly. Double check that one.

Also, I did you force-clean, and build it again.

**Comment by itaibs** [comment]
@alinz, thanks for the reply.

I found the culprit. There is one library I'm not linking in the share extension, which is libRNFIRMessaging.a. This is a library used for react-native-fcm (for handling push notifications).

Linking it to the share extension creates a whole new class of issues which I prefer to avoid. I am not using this package at all in the share extension (obviously, no need to handle push notifications in the extension, only in the main app). So is there a way to avoid this error without linking this library?

Thanks!

**Comment by alinz** [comment]
@itaibs, I'm using that `react-native-fcm` for my app and I don't need to link to the that. notification only available for app not share extension and you should not link with that or your app will be rejected.

also I have attached the the list of library which I linked with my share extension.

![screen shot 2017-07-24 at 11 02 30 am](https://user-images.githubusercontent.com/967050/28529831-9a0d5e64-705f-11e7-8410-ec36aeacbda3.png)

**Comment by itaibs** [comment]
@alinz I see. So I'm guessing there is something very basic I am not getting here, and would love some clarification.

Here's what I did to try and isolate the issue. My index.ios.js is as basic as it gets:

`import './shim.js';

import { AppRegistry } from 'react-native';

import Root from './src/components/root';
import Share from './src/components/share';

AppRegistry.registerComponent('QueueShare', () => Share);
AppRegistry.registerComponent('Queue', () => Root);
`

In my Share component, there is no dependency on react-native-fcm.

Obviously, in my Root component there are dependencies on react-native-fcm.

If I comment out those dependencies, then the share extension works fine. But if I keep them (again, only the Root component is dependent on them, not the Share component) then I get the "Native module cannot be null" exception and the extension won't load.

How can I make the extension not dependent on react-native-fcm while my main app remain dependent?

Thanks again :)

**Comment by alinz** [comment]
oh that's easy, instead of using `import`, you have to use `require`. I think I ran into this problem. I tried adding some variables to `global`. as you know in react-native, `global` is an object which can be share between all modules during the runtime, similar to `window` in `web`. I tried that but the code becomes too fragile. Then I remember that I have to use require.

so your code should be something like this

```
import './shim.js';

import { AppRegistry } from 'react-native';

AppRegistry.registerComponent('QueueShare', () => require( './src/components/share').default);
AppRegistry.registerComponent('Queue', () => require('./src/components/root').default);
```

with this approach, only those modules will be executed that needed.

Let me know if that actually solve your problem.

**Comment by itaibs** [comment]
@alinz This seems to have done the trick!
Thanks a lot for walking me through this :)
