### ISSUE TITLE
Question on communication with share extension and main app

### ISSUE THREAD

**Issue by adambmc** [alinz/react-native-share-extension#51]
Hi, thanks for this component.

On iOS all its fine configured and running, also I used the module [react-native-swiss-knife](https://github.com/alinz/react-native-swiss-knife) to enables sharing the URL value between share extension and the main app (workes fine).

My question is: how can I notify about the new URL value and open the main app after closing the share extension?

Thanks!

**Comment by alinz** [comment]
as far as I know, you can't use openURL to open any app including the main app from share extension. 

You can let the user know to open your app. if your app is not loaded, then you can get it from react-native-swiss-knife. if your app is already launched, you have to use [App State](https://facebook.github.io/react-native/docs/appstate.html) to detect opening your app and check if a new value has been added or not.

I will close this ticket, but feel free to continue the discussion.

**Comment by adambmc** [comment]
Thanks for your quick response.

I manged to do it with openURL- first i set the URL scheme ([Register URL Schemes](http://johnsonsu.com/react-native-custom-url-scheme-launch-apps-using-linking/)), then i tried to implement it with RN but i couldn't make work, so i did it with Objective-C ([openURL Deprecated in iOS 10](https://useyourloaf.com/blog/querying-url-schemes-with-canopenurl/))

**Comment by isaachinman** [comment]
@adambmc Can you explain a bit more about how you achieved this? As @alinz says, you are not really supposed to be able to use `openURL` inside share extensions on iOS.

**Comment by matejkriz** [comment]
@isaachinman You could use `openURL` method of `NSExtensionContext`: https://developer.apple.com/documentation/foundation/nsextensioncontext/1416791-openurl?language=objc

Here is the implementation of native module for Today Widget: https://github.com/matejkriz/react-native-today-widget/blob/master/ios/TodayWidgetExtension/Linking.m

**Comment by isaachinman** [comment]
@matejkriz Unless I misunderstood, that only applies to Today extensions. This utility, `react-native-share-extension`, specifically works with Share extensions. It seems like your proposed solution avoids this repository completely?

**Comment by matejkriz** [comment]
@isaachinman I believe you could reimplement the same for `react-native-share-extension`. Share extension also use `NSExtensionContext`: https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/Share.html#//apple_ref/doc/uid/TP40014214-CH12-SW1

**Comment by matejkriz** [comment]
@isaachinman BTW: https://github.com/alinz/react-native-share-extension/pull/67/files

**Comment by isaachinman** [comment]
Ah wow! I had no idea you had a PR open. There are several PRs open for this project that add extremely useful functionality (eg multi-image support, and this). I will check it out now. Thanks!

**Comment by matejkriz** [comment]
It's not mine PR, I just have it in bookmarks because I was looking for inspiration for react-native-today-widget...

**Comment by isaachinman** [comment]
Yeah, I saw that as soon as I opened it. It's a familiar face, @birkir. I assume he has deployed apps with Apples approval containing this method (?).

**Comment by birkir** [comment]
Yes, this method passes apple's approval 👍
