### ISSUE TITLE
How to Get Extension to Show up In Safari Share

### ISSUE THREAD

**Issue by Faolain** [alinz/react-native-share-extension#52]
Hey great work Alinz. I followed all the instructions for installation and the build succeeded. However I'm having trouble seeing the extension show up when I press "Share" on Safari on the iOS Simulator. I press "More" and see the only default apps of Facebook, Twitter, and Reminders. How do I make my extension show up there? Is there a particular file which I should double check to make sure is edited?

**Comment by alinz** [comment]
if you can't see the extension app show up then you might have done/missed something during creating a new new share extension [here](https://github.com/alinz/react-native-share-extension#ios). double check the doc. if you couldn't be able to resolve it send me the example repo and I will look into it

**Comment by Faolain** [comment]
Thanks alinz! I went over the steps again...and now it pops up. I guess it's possible I simply missed something although I had already gone over the steps twice before. As a follow-up question I used the extension example you have with the modal but when selected in the simulator, nothing happens. In addition the safari browser page seems to be "locked". Have you encountered this before?

**Comment by alinz** [comment]
can you also add [this](https://github.com/alinz/react-native-share-extension#test-on-device-without-dev-server)

**Comment by Faolain** [comment]
Just added. Build on Xcode still succeeds(Also Cleaning before just in case). However now when I try to run 

`react-native run-ios`

I get the following in my terminal which prevents the ios simulator from opening up now.

<img width="980" alt="screen shot 2017-08-13 at 4 13 39 pm" src="https://user-images.githubusercontent.com/9613083/29253074-6f42f1ba-8042-11e7-9d0f-9ee68d8824bb.png">

**Comment by Faolain** [comment]
Update: Not sure what I did but it works now. The only difference was that instead of just adding the selected libraries you have listed I added everything except *.tvos files. For anyone who is having trouble thats what did it for me. Thanks so much alinz!
