### ISSUE TITLE
Does this support iOS 8 and iOS9?

### ISSUE THREAD

**Issue by wootwoot1234** [alinz/react-native-share-extension#54]
Does this support iOS 8 and iOS9?

**Comment by alinz** [comment]
Yes, share extension is introduced by apple in ios 8. so technically you can use it. I'm gonna close this but do you mind explaining why are you asking this?

**Comment by wootwoot1234** [comment]
Great.  I ask because I'm using another module that seems to be crashing my
app when used on iOS 9.  I just wanted to make sure before I spent the time
to switch over to this module.

**Comment by alinz** [comment]
remember one thing, share extension doesn't support some native modules, such as Notification. So when you are using it, make sure that you are not loading any native modules. look into this https://github.com/alinz/react-native-share-extension/issues/48#issuecomment-317587122
