### ISSUE TITLE
macOS (OSX) share extension possible?

### ISSUE THREAD

**Issue by mweichert** [alinz/react-native-share-extension#59]
Is it possible to run this on macOS as well? I haven't found any node share extensions yet for macOS.

**Comment by alinz** [comment]
@mweichert I don't think so. This is tightly couple to ios and android platform.  You are more than welcome to fork the project and make it work for macOS.

I'm still doesn't know what you are trying to do.  

closing this as this is not related to this project. But you are welcome to continue the discussion here.
