### ISSUE TITLE
Android - when show the app share, the area is with padding

### ISSUE THREAD

**Issue by nicholasess** [alinz/react-native-share-extension#68]
![screen shot 2017-11-21 at 3 18 13 pm](https://user-images.githubusercontent.com/3238901/33088707-8ca39b7e-ced5-11e7-9274-b3cb1c876ca8.png)

react-native 0.45
android 5.0

**Comment by max-prokopenko** [comment]
Setting `<item name="android:windowIsFloating">` to `false` in styles.xml solves this isses

**Comment by karlAlnebratt** [comment]
@max-prokopenko thanks for the help. that work 👍

**Comment by nicholasess** [comment]
@max-prokopenko thanks too
