### ISSUE TITLE
Compile warning: Embedded binary's NSExtensionActivationRule is TRUEPREDICATE

### ISSUE THREAD

**Issue by npomfret** [alinz/react-native-share-extension#7]
I've just tried to install this for the first time.  When I compiled I saw this worrying warning:

`warning: Embedded binary's NSExtensionActivationRule is TRUEPREDICATE. Before you submit your containing app to the App Store, be sure to replace all uses of TRUEPREDICATE with specific predicate statements or NSExtensionActivationRule keys. If any extensions in your containing app include TRUEPREDICATE, the app will be rejected.
`

Not sure what it means though, or how to get rid of it but it looks important.  Any ideas?

**Comment by npomfret** [comment]
Did some reading.  Think i understand now.

**Comment by lazee** [comment]
@npomfret I have the same problem. Could you hint on how you solved it?

**Comment by npomfret** [comment]
I wasn't following the instructions properly, thats all.  But I never got this to work in my app and gave up after a while.  I'm going to try again soon.  I got the example working, and even reproduced the example from scratch so I'm pretty sure this module works.  Good luck

**Comment by alinz** [comment]
basically, what it says that you have to tell what your share extension intend to do. Apple needs to know what you want to do and it's pretty simple to setup. this error has nothing to do with this module.

What you have to do is go to your share extension's plist and change it the way you want to intract with user.

Here's an example of our production app.

![screen shot 2016-10-26 at 10 28 04 am](https://cloud.githubusercontent.com/assets/967050/19730077/0f35d6d6-9b67-11e6-8544-d1d48bb88bc3.png)
