### ISSUE TITLE
ShareExtension "screen" doesn´t appear

### ISSUE THREAD

**Issue by BigPun86** [alinz/react-native-share-extension#85]
I have followed the instructions and double checked it many times but coulnd´t find any difference in the code. When i try to share an image or an url the photo app or safari app freezes. Now i really have no idea what the reason could be, but maybe it has to do something with my js code and my structure i am using? i have no main index file i am using the classic index.android & index.ios and within my src folder i have my share.js file which has the code exactly like in the sample. In the index.ios / android i am registeruing first my app and then directly under it the ShareEx. Any ideas where to start or how to fix this? 

**Environment**
    "react": "^16.0.0-beta.5",
    "react-native": "0.53.3",
    "react-native-share-extension": "^1.2.1"

***Update***
Okay, i just found out that it might not have been frozen. In my ShareEx.m file i define the rootView.backgroundColor to be nil (from example) which makes the view completely transparent as soon as i want to share something with my app. So when i change this to a color i will see it but nothing else happens.

**Comment by Saad-Bashar** [comment]
Did you figure it out @BigPun86? I also changed the color but nothing happened.

**Comment by NikitaPokryshko** [comment]
@BigPun86 Hi! Had you solve these problems? The same behavior and I don't know how to move on.

**Comment by BigPun86** [comment]
@Saad-Bashar and @NikitaPokryshko in my case i haven't correctly added all my linked libraries in xcode for both targets. You can find my setup [here](https://github.com/alinz/react-native-share-extension/issues/79#issuecomment-381621597) maybe this will help u?

**Comment by NikitaPokryshko** [comment]
@BigPun86  Thank you. I checked this out but my share extension still behave the same way. Can you explain, please, what did you add except that it was stated in the installation instructions?

**Comment by NikitaPokryshko** [comment]
@BigPun86 It works, the problem was at google signin packages. Thank you for link!

**Comment by martinlavanant** [comment]
Hey guys,
I'm actually struggling with the same problem, I linked the same libraries for both targets but still nothing.
For my project I just have an index.js and no separates indexes for iOS and Android. I updated the content of the jsCodeLocation in my extension implementation to "index" instead of "index.ios" I don't know if this could be the problem.

Thanks in advance
