### ISSUE TITLE
The share extension is not available on iOS device

### ISSUE THREAD

**Issue by linweigao** [alinz/react-native-share-extension#90]
Thank you for the great lib and I have made everything work on the simulator, but once I deploy the release version to my iOS device. It seems the share extension is not registered.

Anyone know how to fix that?

**Comment by NikitaPokryshko** [comment]
@linweigao What react-native version do you use?

**Comment by igorkulka** [comment]
@linweigao I have the same problem even if I run debug version on real iOS device (iphone 5s). Simulator works great. Do you already have any solution? @NikitaPokryshko my version "react-native": "0.52.0"

**Comment by NikitaPokryshko** [comment]
Did you complete all steps in both platforms? 
I can't make it works correctly and thought the library does not support the latest versions of react native. 
Also I have a question about index.js: do you make 2 index.js files for ios and android?

Thank you in advance

**Comment by NikitaPokryshko** [comment]
@igorkulka Did you complete all steps in both platforms? 
I can't make it works correctly and thought the library does not support the latest versions of react native. 
Also I have a question about index.js: do you make 2 index.js files for ios and android?

**Comment by linweigao** [comment]
react-native: 0.54.4
I can make it work in iOS with simulator, but the sharing extension is not available after I deploy it to a real device.
I guess it is a bundle issue.

**Comment by linweigao** [comment]
@NikitaPokryshko I have a shared index.js, but you can make 2 different js if you want. Here is my repro: https://github.com/linweigao/react-native-app-share-extension which has iOS app integrated already.

**Comment by igorkulka** [comment]
@linweigao I found out that I had deployement target for the extension in xcode set for ios 11.3 but I deployed it to ios 11.2.6

**Comment by igorkulka** [comment]
@NikitaPokryshko I just tried to make it run for iOS

**Comment by linweigao** [comment]
@NikitaPokryshko thx. You nailed it. The iOS version matters.

**Comment by NikitaPokryshko** [comment]
@linweigao Thank you very much! It works! You saved me from the headache for today =))
@igorkulka Thanks for you too, this is valuable information, I suppose that I will also face this in the near future
