### ISSUE TITLE
iOS Share Extension RN App doesn't mount

### ISSUE THREAD

**Issue by AndrewHenderson** [alinz/react-native-share-extension#94]
iOS 11.3
RN 0.54.2

I'm finding that [instantiating the `rootView`](https://github.com/alinz/react-native-share-extension/blob/master/examples/Sample1/ios/MyShareEx/MyShareEx.m#L19-L32) doesn't actually lead to the `React.Component` lifecycle methods in [here](https://github.com/alinz/react-native-share-extension/blob/master/examples/Sample1/share.ios.js#L17-L36) being executed.

The rootView does appear, however, no React components are present. It's just the empty storyboard View.

@alinz The following code does not seem to actually initialize the Share App in our JS code.

```js
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"MyShareEx"
                                               initialProperties:nil
                                                   launchOptions:nil];
```
You can change the jsCodeLocation to  #`@"foo.ios"` or the module name to `@"Foo"` and the outcome is the same.

**Comment by isaachinman** [comment]
@AndrewHenderson Did you find a solution to this? Encountered the same thing.

**Comment by AndrewHenderson** [comment]
@isaachinman I created a clean project and got the extension working. Then copied all of my files over to the new Xcode project. It continued to work in Debug configuration. However, I have not gotten it to work on Release configuration.

**Comment by isaachinman** [comment]
Have you seen the [Test on Device without dev-server](https://github.com/alinz/react-native-share-extension#test-on-device-without-dev-server) section of the docs? Might help you.

**Comment by isaachinman** [comment]
Yes. As far as I know, several devs have release apps in both stores with this share extension included.

**Comment by AndrewHenderson** [comment]
@isaachinman I'm currently running a reduced test case. I was able to get the extension working in **Release mode** on a boilerplate project that uses only this library.

There were three important steps to getting it working:

1) I added the [test on device without dev server script](https://github.com/alinz/react-native-share-extension#test-on-device-without-dev-server).
2) Make sure your app and the extension use the same index.js file for registering the React Native App and that you use `require` syntax rather than `import`.
```jsx
const ReactNative = require('react-native');
const { AppRegistry } = ReactNative;
const App = require('./App').default;
const Share = require('./Share').default;

AppRegistry.registerComponent('AwesomeProject', () => App);
AppRegistry.registerComponent('MyShareEx', () => Share);
```
3) Add following in the extension's info.plist:
```
<key>NSExtensionActivationRule</key>
<dict>
  <key>NSExtensionActivationSupportsImageWithMaxCount</key>
  <integer>1</integer>
</dict>
```
I still can't get it to work on my app. I suspect because my app requires access to certain APIs that are not allowed for use by extensions.

**Comment by isaachinman** [comment]
Not sure about the `require` vs `import` thing (probably a red herring), but I believe those other steps are already in the docs.

**Comment by AndrewHenderson** [comment]
@isaachinman You were right. It wasn't necessary.

I was able to get everything working in both Debug and Release mode.

Thanks.

**Comment by isaachinman** [comment]
@AndrewHenderson That is correct, it's an annoying part of working with such a "bare bones" RN application. Some people have included JS-based devtools, etc.

Glad to hear you got it working!
